import './globals.css'
import { Noto_Sans } from 'next/font/google'

const noto = Noto_Sans({
  weight: ['400', '500', '700', '900',],
  subsets: ['latin']
});

export const metadata = {
  title: 'ApiProd',
  description: 'Generated by create next app',
}
import dynamic from 'next/dynamic';

const DynamicNavbar = dynamic(() => import('../components/common/Navbar'), { ssr: false });

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/images/logo.svg' />
      </head>
      <body className={noto.className}>
        <DynamicNavbar />
        {children}</body>
    </html>
  )
}
