import Header from '@/components/common/Header';
import './globals.css'
import { Noto_Sans } from 'next/font/google'
import { Footer } from '@/components/common/Footer';

const noto = Noto_Sans({
  weight: ['400', '500', '700', '900',],
  subsets: ['latin']
});

export const metadata = {
  title: 'ApiProd',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/images/logo.svg' />
      </head>
      <body className={noto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
